//= require_self
//= require jquery
//= require jquery_ujs
//= require bootstrap
//= require twitter/bootstrap
//= require jquery-ui
//= require_tree ./shared
//= require lib/jquery.quicksearch
//= require lib/encoding.js
//= require lib/jquery.velocity.min
//= require lib/jquery.jgrowl.js
//= require local/lib/api-connector.js
//= require lib/jquery.multi-select
//= require lib/jquery.quicksearch
//= require lib/bootstrap-multiselect
//= require lib/jquery.tablesorter.min
//= require jquery-fileupload/basic
